# Generated by Django 6.1 on 2026-08-26 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0002_user_failed_login_attempts_user_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catsubmission',
            name='cat_file',
            field=models.FileField(blank=True, help_text='The CAT question paper (PDF) students download.', null=True, upload_to='cat_papers/'),
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='lecture_notes/')),
                ('is_published', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_notes', to='portal_api.lecturerunitallocation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
