# Generated by Django 6.1 on 2026-08-27 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0003_catsubmission_cat_file_lecturenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="True once the department's COD has reviewed and signed off this entered grade."),
        ),
        migrations.AddField(
            model_name='grade',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_grades', to=settings.AUTH_USER_MODEL),
        ),
    ]
