# Generated by Django 6.1 on 2026-08-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0004_grade_is_verified_grade_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'System Admin'), ('student', 'Student'), ('lecturer', 'Lecturer'), ('staff', 'Staff'), ('registrar', 'Registrar'), ('dean', 'Dean'), ('cod', 'Chairman of Department'), ('hostel_warden', 'Hostel Warden'), ('finance', 'Finance Officer'), ('exam_office', 'Examinations Office'), ('librarian', 'Librarian')], max_length=20),
        ),
    ]
