# Generated by Django 6.1 on 2026-08-30 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bypass_result_check', models.BooleanField(default=False)),
                ('bypass_reason', models.TextField(blank=True)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_count', models.IntegerField(default=0)),
                ('graduated_count', models.IntegerField(default=0)),
                ('suspended_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_runs', to='portal_api.academicyear')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_runs', to='portal_api.faculty')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_runs', to='portal_api.programme')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.IntegerField()),
                ('from_semester', models.IntegerField()),
                ('to_year', models.IntegerField(blank=True, null=True)),
                ('to_semester', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('promoted', 'Promoted'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('skipped', 'Skipped'), ('already_promoted', 'Already Promoted (skipped)')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('outstanding_supplementary_count', models.IntegerField(default=0)),
                ('was_bypassed', models.BooleanField(default=False, help_text='True if this student was promoted despite outstanding/incomplete results because the run had bypass_result_check=True.')),
                ('invoice_error', models.CharField(blank=True, max_length=255)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_api.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='portal_api.student')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='portal_api.promotionrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'from_year', 'from_semester'], name='portal_api__student_120f14_idx')],
            },
        ),
    ]
