# Generated by Django 6.1 on 2026-08-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0006_promotionrun_promotionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kcse_index_number',
            field=models.CharField(blank=True, db_index=True, help_text='KCSE index number, e.g. 12345678001/2024.', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='kcse_mean_grade',
            field=models.CharField(blank=True, help_text='Overall KCSE mean grade, e.g. B+.', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='kcse_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='KCSE mean points, e.g. 9.50.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, help_text='Secondary school the student joined from.', max_length=150),
        ),
    ]
