# Generated by Django 6.1 on 2026-08-31 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_api', '0007_student_kcse_index_number_student_kcse_mean_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbooking',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_bookings', to='portal_api.invoice'),
        ),
        migrations.AlterField(
            model_name='hostelbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('pending_payment', 'Pending Payment'), ('approved', 'Approved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='HostelFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_fee_structures', to='portal_api.academicyear')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='portal_api.hostel')),
            ],
            options={
                'unique_together': {('hostel', 'academic_year')},
            },
        ),
    ]
