# Generated by Django 6.1 on 2026-08-31 11:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal_api', '0008_hostelbooking_invoice_alter_hostelbooking_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('biometric', 'Biometric Scanner'), ('qr', 'QR Kiosk')], max_length=15)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_salary'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('days_per_year', models.IntegerField(default=21)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('carry_forward_allowed', models.BooleanField(default=False)),
                ('max_carry_forward_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=15)),
                ('is_taxable', models.BooleanField(default=True, help_text='Allowances only — counts toward PAYE taxable pay.')),
                ('is_statutory', models.BooleanField(default=False, help_text='PAYE/NSSF/SHIF/Pension — computed, not manually set.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PAYEBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_year', models.IntegerField()),
                ('band_order', models.IntegerField(help_text='1 = lowest band, ascending.')),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Blank = no upper limit (top band).', max_digits=10, null=True)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['effective_year', 'band_order'],
                'unique_together': {('effective_year', 'band_order')},
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('processing', 'Processing'), ('closed', 'Closed (Payslips Generated)'), ('paid', 'Paid')], default='open', max_length=15)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods', to='portal_api.academicyear')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=15)),
                ('staff_count', models.IntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payroll_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run', to='hr.payrollperiod')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nssf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shif', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pension_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_statutory_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payrollperiod')),
            ],
            options={
                'ordering': ['-payroll_period__year', '-payroll_period__month'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_academic', models.BooleanField(default=False, help_text='True for teaching positions (lecturers, tutors).')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_positions', to='portal_api.department')),
                ('job_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='hr.jobgroup')),
            ],
            options={
                'unique_together': {('title', 'department')},
            },
        ),
        migrations.CreateModel(
            name='QRAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('valid_date', models.DateField(default=django.utils.timezone.localdate)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='portal_api.department')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayslipLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='hr.payslip')),
                ('component_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.salarycomponenttype')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(default='Staff Loan', max_length=50)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('repayment_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='hr.payrollperiod')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='hr.staffloan')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('permanent', 'Permanent & Pensionable'), ('contract', 'Contract Staff'), ('part_time', 'Part-Time'), ('casual', 'Casual')], default='permanent', max_length=20)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('retired', 'Retired')], default='active', max_length=20)),
                ('date_of_joining', models.DateField(default=django.utils.timezone.now)),
                ('date_of_exit', models.DateField(blank=True, null=True)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('nssf_number', models.CharField(blank=True, max_length=30)),
                ('shif_number', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=100)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_staff', to='portal_api.department')),
                ('job_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='hr.jobgroup')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holders', to='hr.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_hr_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='staffloan',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='hr.staffprofile'),
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('biometric', 'Biometric'), ('qr', 'QR Code'), ('manual', 'Manual Entry')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('excused', 'Excused')], default='present', max_length=10)),
                ('late_minutes', models.IntegerField(default=0)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.staffprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('repayment_months', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fully_recovered', 'Fully Recovered')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_approved', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='hr.staffprofile')),
            ],
        ),
        migrations.AddField(
            model_name='payslip',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.staffprofile'),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('accrued_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carried_forward_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='hr.leavetype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='leave_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_reviews', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hr.leavetype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='hr.staffprofile')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('fixed_term', 'Fixed Term'), ('part_time', 'Part-Time'), ('casual', 'Casual')], max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Blank for permanent contracts.', null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('is_active', models.BooleanField(default=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='hr.employmentcontract')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='hr.position')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.staffprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('component_type', models.ForeignKey(limit_choices_to={'category': 'deduction'}, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_grants', to='hr.salarycomponenttype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='hr.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BiometricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='hr.attendancedevice')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_logs', to='hr.staffprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('component_type', models.ForeignKey(limit_choices_to={'category': 'allowance'}, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_grants', to='hr.salarycomponenttype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='hr.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StatutoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('nssf', 'NSSF'), ('shif', 'SHIF'), ('pension', 'Pension')], max_length=10)),
                ('effective_year', models.IntegerField()),
                ('rate_employee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rate_employer_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fixed_amount_employee', models.DecimalField(blank=True, decimal_places=2, help_text='Used instead of a percentage where the scheme is a flat fee.', max_digits=10, null=True)),
                ('min_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'unique_together': {('scheme', 'effective_year')},
            },
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['staff_number'], name='hr_staffpro_staff_n_c43df9_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['employment_status'], name='hr_staffpro_employm_6516cd_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['staff', 'date'], name='hr_staffatt_staff_i_f4992a_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['date', 'status'], name='hr_staffatt_date_57be62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('staff', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('staff', 'payroll_period')},
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('staff', 'leave_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['staff', 'status'], name='hr_leaveapp_staff_i_99e5bd_idx'),
        ),
    ]
